artist:
  name: Dallas McGree
  tagline: Actor, Composer, Singer-Songwriter, and Storyteller
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/DallasMcGee.RedDirtMusic/
  - name: Instagram
    url: https://instagram.com/hindsight_musings
  - name: Patreon
    url: https://www.patreon.com/thomashindsmusic
  - name: Youtube
    url: https://www.youtube.com/channel/UCg8UMRt1LCFo3az2DffO2tw
  - name: Apple
    url: https://music.apple.com/us/artist/thomas-hinds/1004862632
  - name: Spotify
    url: https://open.spotify.com/artist/7wOxMZgaCVFRwfRT9tvqDH

site_language: en
