artist:
  name: Dallas McGree
  tagline: Actor, Composer, Singer-Songwriter, and Storyteller
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/DallasMcGee.RedDirtMusic/
  - name: Youtube
    url: https://www.youtube.com/channel/UCg8UMRt1LCFo3az2DffO2tw

site_language: en
