navigation:
  - text: Shows
    url: "#shows"
  - text: Contact
    url: "#contact"
  - text: Merch
    url: https://www.storefrontier.com/dallasmcgee
  - text: Guitars
    url: https://www.smoothstoneguitars.com/
